trigger:
- main

pool:
  name: 'MyProjectAgentPool'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Ensure correct .NET SDK is installed
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'     # or 6.x/7.x depending on your project

# Restore using dotnet (not NuGet)
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Build
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Test
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Publish artifacts
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'